# Generated by Django 3.1 on 2021-04-08 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('careta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_number', models.IntegerField(default=0)),
                ('job_type', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_desc', models.CharField(max_length=100)),
                ('job_remarks', models.CharField(max_length=100)),
                ('job_startdate', models.DateField()),
                ('job_enddate', models.DateField()),
                ('job_startdate_actual', models.DateField()),
                ('job_enddate_actual', models.DateField()),
                ('job_actualdays', models.IntegerField(blank=True, default=0, null=True)),
                ('job_status_fm', models.CharField(max_length=50)),
                ('job_status_mn', models.CharField(max_length=50)),
                ('job_scheduledate', models.DateField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TaskCar', to='careta.car')),
                ('job_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TaskJO', to='jobscheduling.joborder')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TaskMgr', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FieldManAssignment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fieldman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FieldmanId', to=settings.AUTH_USER_MODEL)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FieldmanTask', to='jobscheduling.task')),
            ],
        ),
    ]
