# Generated by Django 3.1 on 2021-04-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobscheduling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='job_status_fm',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='job_status_mn',
            field=models.BooleanField(default=False),
        ),
    ]
