# Generated by Django 3.1 on 2021-07-21 05:42

from django.db import migrations, models
import image.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.IntegerField(default=0)),
                ('image_name', models.CharField(max_length=20)),
                ('images', models.ImageField(blank=True, null=True, upload_to=image.utils.upload_path)),
                ('mode', models.CharField(choices=[('cu', 'Careta User'), ('ci', 'Car Inventory'), ('dr', 'Driver Reports'), ('cr', 'Careta Reports')], max_length=2)),
            ],
        ),
    ]
