# Generated by Django 3.1 on 2021-08-17 05:50

from django.db import migrations
import django_resized.forms
import image.utils


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0003_auto_20210810_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=100, size=[892, 408], upload_to=image.utils.upload_path),
        ),
    ]
