# Generated by Django 3.1 on 2021-09-07 07:22

from django.db import migrations, models
import django_resized.forms
import image.utils


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0004_auto_20210817_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=100, size=[700, 300], upload_to=image.utils.upload_path),
        ),
        migrations.AlterField(
            model_name='image',
            name='mode',
            field=models.CharField(choices=[('cu', 'Careta User'), ('ci', 'Car Inventory'), ('dr', 'Driver Reports'), ('cr', 'Careta Reports'), ('cl', 'Check List'), ('ir', 'IR')], max_length=2),
        ),
    ]
