# Generated by Django 3.1 on 2021-11-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0005_auto_20210907_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='mode',
            field=models.CharField(choices=[('cu', 'Careta User'), ('ci', 'Car Inventory'), ('dr', 'Driver Reports'), ('cr', 'Careta Reports'), ('cl', 'Check List'), ('ir', 'IR'), ('fi', 'Field Inspection'), ('dp', 'Damage Parts')], max_length=2),
        ),
    ]
