# Generated by Django 3.1 on 2021-07-08 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_auto_20210705_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='cr_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='or_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
