# Generated by Django 3.1 on 2021-09-22 04:58

import car.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_auto_20210708_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFupload',
            fields=[
                ('pdf_id', models.AutoField(primary_key=True, serialize=False)),
                ('pdf', models.FileField(blank=True, null=True, upload_to=car.models.upload_path)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pdf', to='car.car')),
            ],
        ),
    ]
