# Generated by Django 3.1 on 2021-09-22 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_auto_20210922_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='pdf',
            name='date_updated',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
