# Generated by Django 3.1 on 2021-10-08 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0007_auto_20210922_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='car',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pdf', to='car.car'),
        ),
    ]
