# Generated by Django 3.1 on 2021-10-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0008_auto_20211008_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes'),
        ),
    ]
