# Generated by Django 3.1 on 2021-10-15 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0009_car_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='QR-Codes'),
        ),
    ]
