# Generated by Django 3.1 on 2022-01-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0010_auto_20211015_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='release_year',
            field=models.IntegerField(blank=True, default=2022, null=True),
        ),
    ]
