# Generated by Django 3.1 on 2021-05-28 09:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('car', '0001_initial'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('inspection_id', models.AutoField(primary_key=True, serialize=False)),
                ('mileage', models.IntegerField(default=0)),
                ('gps', models.CharField(blank=True, max_length=255, null=True)),
                ('cleanliness_exterior', models.BooleanField(default=False)),
                ('condition_rust', models.BooleanField(default=False)),
                ('decals', models.BooleanField(default=False)),
                ('windows', models.BooleanField(default=False)),
                ('rear_door', models.BooleanField(default=False)),
                ('mirror', models.BooleanField(default=False)),
                ('roof_rack', models.BooleanField(default=False)),
                ('rear_step', models.BooleanField(default=False)),
                ('seats', models.BooleanField(default=False)),
                ('seat_belts', models.BooleanField(default=False)),
                ('general_condition', models.BooleanField(default=False)),
                ('vehicle_documents', models.BooleanField(default=False)),
                ('main_beam', models.BooleanField(default=False)),
                ('dipped_beam', models.BooleanField(default=False)),
                ('side_lights', models.BooleanField(default=False)),
                ('tail_lights', models.BooleanField(default=False)),
                ('indicators', models.BooleanField(default=False)),
                ('break_lights', models.BooleanField(default=False)),
                ('reverse_lights', models.BooleanField(default=False)),
                ('hazard_light', models.BooleanField(default=False)),
                ('rear_fog_lights', models.BooleanField(default=False)),
                ('interior_lights', models.BooleanField(default=False)),
                ('screen_washer', models.BooleanField(default=False)),
                ('wiper_blades', models.BooleanField(default=False)),
                ('horn', models.BooleanField(default=False)),
                ('radio', models.BooleanField(default=False)),
                ('front_fog_lights', models.BooleanField(default=False)),
                ('cleanliness_engine_bay', models.BooleanField(default=False)),
                ('washer_fluid', models.BooleanField(default=False)),
                ('coolant_level', models.BooleanField(default=False)),
                ('brake_fluid_level', models.BooleanField(default=False)),
                ('power_steering_fluid', models.BooleanField(default=False)),
                ('liquid_leak', models.BooleanField(default=False)),
                ('gas_level', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1)),
                ('oil_level', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1)),
                ('tyres', models.BooleanField(default=False)),
                ('front_visual', models.BooleanField(default=False)),
                ('rear_visual', models.BooleanField(default=False)),
                ('spare_visual', models.BooleanField(default=False)),
                ('wheel_brace', models.BooleanField(default=False)),
                ('jack', models.BooleanField(default=False)),
                ('front_right_wheel', models.BooleanField(default=False)),
                ('front_left_wheel', models.BooleanField(default=False)),
                ('rear_right_wheel', models.BooleanField(default=False)),
                ('rear_left_wheel', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('body_no', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='inspection', to='car.car')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to=settings.AUTH_USER_MODEL)),
                ('edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edited_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('repair_id', models.AutoField(primary_key=True, serialize=False)),
                ('ir_no', models.CharField(blank=True, max_length=30, null=True)),
                ('incident_date', models.DateField(default=datetime.date.today)),
                ('date_receive', models.DateField(default=datetime.date.today)),
                ('site_poc', models.CharField(blank=True, max_length=30, null=True)),
                ('contact_no', models.IntegerField(blank=True, default=0, null=True)),
                ('incident_details', models.TextField(blank=True, max_length=200, null=True)),
                ('perform_date', models.DateField(default=datetime.date.today)),
                ('actual_findings', models.TextField(blank=True, max_length=200, null=True)),
                ('actual_remarks', models.TextField(blank=True, max_length=200, null=True)),
                ('repair_date', models.DateField(default=datetime.date.today)),
                ('action_taken', models.TextField(blank=True, max_length=200, null=True)),
                ('date_done', models.DateField(default=datetime.date.today)),
                ('status_repair', models.CharField(blank=True, max_length=20, null=True)),
                ('remarks', models.TextField(blank=True, max_length=200, null=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('diagnosed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosed', to=settings.AUTH_USER_MODEL)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated', to=settings.AUTH_USER_MODEL)),
                ('job_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='repair', to='task.joborder')),
                ('noted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noted', to=settings.AUTH_USER_MODEL)),
                ('repair_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repair', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InspectiontImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='images/')),
                ('report', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='report.inspection')),
            ],
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('cost_id', models.AutoField(primary_key=True, serialize=False)),
                ('cost_type', models.CharField(choices=[('P', 'Parts'), ('L', 'Labor')], default='L', max_length=1)),
                ('particulars', models.CharField(max_length=50)),
                ('cost', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('date_updated', models.DateField(auto_now=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('ro_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost', to='report.repair')),
            ],
        ),
    ]
