# Generated by Django 3.1 on 2021-08-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20210804_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repair',
            name='contact_no',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
