# Generated by Django 3.1 on 2021-08-17 05:50

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20210804_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckList',
            fields=[
                ('check_list_id', models.AutoField(primary_key=True, serialize=False)),
                ('schedule_date', models.DateField(default=datetime.date.today)),
                ('odometer', models.IntegerField(blank=True, default=0, null=True)),
                ('job_desc', models.CharField(choices=[('in', 'Inspection'), ('re', 'Repair'), ('pm', 'PMS')], default='pm', max_length=2)),
                ('pair_ewd', models.BooleanField(default=False)),
                ('color_ewd', models.CharField(choices=[('yo', 'Yellow only'), ('ro', 'Red only'), ('bo', 'both')], default='bo', max_length=2)),
                ('body_no_ewd', models.BooleanField(default=False)),
                ('body_no_fl_tire', models.BooleanField(default=False)),
                ('body_no_fr_tire', models.BooleanField(default=False)),
                ('body_no_rl_tire', models.BooleanField(default=False)),
                ('body_no_rr_tire', models.BooleanField(default=False)),
                ('spare_tire', models.BooleanField(default=False)),
                ('body_no_batt', models.BooleanField(default=False)),
                ('vehicle_wt', models.BooleanField(default=False)),
                ('parts_included', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Unit is in good condition'), (1, 'Cracked windshield'), (2, 'Rough idling, Cleaned and adjust throttle valve'), (3, 'For warranty'), (4, 'For body repair'), (5, 'Concern out of scope'), (6, 'Worn out brake pads'), (7, 'Worn out brake shoe'), (8, 'Low engine oil'), (9, 'Worn out drive belt'), (10, 'Others')], max_length=22, null=True)),
                ('remarks', models.TextField(blank=True, max_length=200, null=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CheckListParts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date_updated', models.DateField(auto_now=True)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CheckListReportParts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('date_updated', models.DateField(auto_now=True)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
