# Generated by Django 3.1 on 2021-08-17 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_checklist_checklistparts_checklistreportparts'),
        ('car', '0003_auto_20210708_1048'),
        ('task', '0002_auto_20210817_1350'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='repair',
            name='body_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b_repair', to='task.ir'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='ir_no',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repair', to='task.ir'),
        ),
        migrations.AddField(
            model_name='checklistreportparts',
            name='check_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='report.checklist'),
        ),
        migrations.AddField(
            model_name='checklistreportparts',
            name='check_list_parts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='report.checklistparts'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='body_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='car.car'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checklist',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='task.task'),
        ),
        migrations.AddField(
            model_name='repair',
            name='check_list',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repair', to='report.checklist'),
        ),
    ]
