# Generated by Django 3.1 on 2021-08-18 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20210817_1350'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0006_auto_20210817_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='schedule_date',
        ),
        migrations.AddField(
            model_name='checklist',
            name='job_order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='task.joborder'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='noted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='check_noted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checklist',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
