# Generated by Django 3.1 on 2021-08-24 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_auto_20210824_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistparts',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
