# Generated by Django 3.1 on 2021-08-25 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_auto_20210824_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistreportparts',
            name='check_list_parts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='report.checklistparts'),
        ),
    ]
