# Generated by Django 3.1 on 2021-08-26 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_auto_20210708_1048'),
        ('report', '0010_auto_20210825_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repair',
            name='body_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b_repair', to='car.car'),
        ),
    ]
