# Generated by Django 3.1 on 2021-09-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0013_auto_20210907_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repair',
            name='contact_no',
        ),
        migrations.RemoveField(
            model_name='repair',
            name='date_receive',
        ),
        migrations.RemoveField(
            model_name='repair',
            name='incident_date',
        ),
        migrations.RemoveField(
            model_name='repair',
            name='incident_details',
        ),
        migrations.RemoveField(
            model_name='repair',
            name='site_poc',
        ),
        migrations.AddField(
            model_name='checklist',
            name='check_list_no',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='body_no_batt',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Other')], default=0),
        ),
    ]
