# Generated by Django 3.1 on 2021-10-13 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0015_repair_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='repair',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='repair',
            name='noted_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
