# Generated by Django 3.1 on 2021-11-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0018_fieldinspection'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldinspection',
            name='acceleration_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldinspection',
            name='air_conditioning_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldinspection',
            name='audio_system_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldinspection',
            name='battery_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldinspection',
            name='belts_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldinspection',
            name='brake_lights_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldinspection',
            name='braking_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldinspection',
            name='breake_system_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldinspection',
            name='carpet_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldinspection',
            name='dashboard_gauges_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldinspection',
            name='dashboard_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldinspection',
            name='defroster_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldinspection',
            name='door_panels_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldinspection',
            name='doors_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldinspection',
            name='drive_axle_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldinspection',
            name='engine_compartment_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldinspection',
            name='engine_performance_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldinspection',
            name='exhaust_system_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldinspection',
            name='fenders_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldinspection',
            name='fluids_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldinspection',
            name='frame_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldinspection',
            name='front_bumber_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldinspection',
            name='front_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldinspection',
            name='fuel_door_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldinspection',
            name='glove_box_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldinspection',
            name='headlights_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldinspection',
            name='headliner_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldinspection',
            name='heater_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldinspection',
            name='hood_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldinspection',
            name='hoses_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldinspection',
            name='idling_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldinspection',
            name='interioir_trim_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldinspection',
            name='mirrors_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldinspection',
            name='non_stock_modif_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldinspection',
            name='oil_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldinspection',
            name='onboard_computer_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldinspection',
            name='pait_condition_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldinspection',
            name='parking_lights_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldinspection',
            name='power_locks_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldinspection',
            name='power_mirrors_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldinspection',
            name='power_seats_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldinspection',
            name='power_steering_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldinspection',
            name='power_windows_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldinspection',
            name='rear_bumper_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldinspection',
            name='rear_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldinspection',
            name='rear_window_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldinspection',
            name='roof_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldinspection',
            name='seats_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldinspection',
            name='signal_lights_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldinspection',
            name='spare_tire_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldinspection',
            name='starting_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldinspection',
            name='steering_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldinspection',
            name='suspension_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldinspection',
            name='suspension_performance_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldinspection',
            name='taillights_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldinspection',
            name='tires_condition_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldinspection',
            name='trans_shift_quality_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldinspection',
            name='transmission_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldinspection',
            name='trim_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldinspection',
            name='trunk_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldinspection',
            name='vanity_mirrors_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldinspection',
            name='wheels_condition_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldinspection',
            name='windows_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldinspection',
            name='windshield_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldinspection',
            name='wiring_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
