# Generated by Django 3.1 on 2021-11-08 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0019_auto_20211108_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fieldinspection',
            old_name='fi_inspection_id',
            new_name='fi_report_id',
        ),
        migrations.RenameField(
            model_name='fieldinspection',
            old_name='front_bumber',
            new_name='front_bumper',
        ),
        migrations.RenameField(
            model_name='fieldinspection',
            old_name='front_bumber_note',
            new_name='front_bumper_note',
        ),
        migrations.RenameField(
            model_name='fieldinspection',
            old_name='comments',
            new_name='summary',
        ),
    ]
