# Generated by Django 3.1 on 2021-11-09 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_merge_20211025_0920'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0020_auto_20211108_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldinspection',
            name='approve_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fi_approve', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fieldinspection',
            name='job_order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_inspection', to='task.joborder'),
        ),
        migrations.AddField(
            model_name='fieldinspection',
            name='noted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fi_noted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fieldinspection',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fieldinspection',
            name='task',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='field_inspection', to='task.task'),
        ),
    ]
