# Generated by Django 3.1 on 2021-11-09 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0021_auto_20211109_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fieldinspection',
            old_name='approve_by',
            new_name='approved_by',
        ),
    ]
