# Generated by Django 3.1 on 2021-11-23 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0024_fieldinspection_operational'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldinspection',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_checklist', to=settings.AUTH_USER_MODEL),
        ),
    ]
