# Generated by Django 3.1 on 2021-11-18 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car', '0010_auto_20211015_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPS',
            fields=[
                ('gps_id', models.AutoField(primary_key=True, serialize=False)),
                ('deviced_id', models.CharField(blank=True, max_length=30, null=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('body_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps', to='car.car')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('updatetime', models.DateTimeField(blank=True, null=True)),
                ('mileage', models.CharField(blank=True, max_length=20, null=True)),
                ('gasolineconsumptionperhour', models.FloatField(default=0)),
                ('gasolineconsumptionperhunkm', models.FloatField(default=0)),
                ('overloaalculate', models.IntegerField(default=0)),
                ('coolanttemperature', models.IntegerField(default=0)),
                ('oilpressure', models.IntegerField(default=0)),
                ('inletbranchpressure', models.IntegerField(default=0)),
                ('inttemperature', models.IntegerField(default=0)),
                ('airmassflow', models.IntegerField(default=0)),
                ('throttleposition', models.IntegerField(default=0)),
                ('oilvalue', models.IntegerField(default=0)),
                ('faultcodeti', models.IntegerField(default=0)),
                ('faultcodes', models.IntegerField(default=0)),
                ('totaldistance', models.IntegerField(default=0)),
                ('statisticsday', models.DateTimeField(blank=True, null=True)),
                ('beginoil', models.IntegerField(default=0)),
                ('endoil', models.IntegerField(default=0)),
                ('addoil', models.IntegerField(default=0)),
                ('leakoil', models.IntegerField(default=0)),
                ('idleoil', models.IntegerField(default=0)),
                ('totaloil', models.IntegerField(default=0)),
                ('totalnotrunningad', models.IntegerField(default=0)),
                ('beginnotrunningad', models.IntegerField(default=0)),
                ('endnotrunningad', models.IntegerField(default=0)),
                ('addnotrunningad', models.IntegerField(default=0)),
                ('leaknotrunningad', models.IntegerField(default=0)),
                ('idlenotrunningad', models.IntegerField(default=0)),
                ('date_updated', models.DateField(auto_now=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='gps.gps')),
            ],
        ),
    ]
