# Generated by Django 3.1 on 2021-11-18 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='obedrecord_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
