# Generated by Django 3.1 on 2021-11-18 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0002_record_obedrecord_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gps',
            old_name='deviced_id',
            new_name='device_id',
        ),
    ]
