# Generated by Django 3.1 on 2021-11-25 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0004_auto_20211123_1031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='overloaalculate',
            new_name='overloadcalculate',
        ),
    ]
