# Generated by Django 3.1 on 2021-11-25 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0005_auto_20211125_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='faultcodeti',
            new_name='faultcodetime',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='inttemperature',
            new_name='inlettemperature',
        ),
    ]
