# Generated by Django 3.1 on 2021-12-01 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0007_auto_20211125_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='faultcodes',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='faultcodetime',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='updatetime',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
