# Generated by Django 3.1 on 2021-12-10 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0008_auto_20211201_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gps',
            name='device_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
