# Generated by Django 3.1 on 2022-01-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0009_auto_20211210_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='endtime',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='starttime',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='statisticsday',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='totaldistance',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
