# Generated by Django 3.1 on 2022-01-14 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0011_auto_20220114_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='starttime',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='statisticsday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
