# Generated by Django 3.1 on 2022-01-14 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0012_auto_20220114_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='totaldistancetoday',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='totaldistance',
            field=models.IntegerField(default=0),
        ),
    ]
