# Generated by Django 3.1 on 2021-07-16 04:49

import careta.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=careta.models.upload_path),
        ),
    ]
