# Generated by Django 3.1 on 2021-03-17 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('careta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('maintenance_id', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=50)),
                ('mileage', models.IntegerField(blank=True, default=0, null=True)),
                ('exterior_body', models.IntegerField(choices=[(1, 'CHECK AND OK'), (2, 'MAY REQUIRE ATTENTION'), (3, 'REQUIRES IMMEDIATE ATTENTION')], default=1)),
                ('windshield', models.IntegerField(choices=[(1, 'CHECK AND OK'), (2, 'MAY REQUIRE ATTENTION'), (3, 'REQUIRES IMMEDIATE ATTENTION')], default=1)),
                ('wipers', models.IntegerField(choices=[(1, 'CHECK AND OK'), (2, 'MAY REQUIRE ATTENTION'), (3, 'REQUIRES IMMEDIATE ATTENTION')], default=1)),
                ('lights', models.IntegerField(choices=[(1, 'CHECK AND OK'), (2, 'MAY REQUIRE ATTENTION'), (3, 'REQUIRES IMMEDIATE ATTENTION')], default=1)),
                ('interior_lights', models.IntegerField(choices=[(1, 'CHECK AND OK'), (2, 'MAY REQUIRE ATTENTION'), (3, 'REQUIRES IMMEDIATE ATTENTION')], default=1)),
                ('ac_operation', models.IntegerField(choices=[(1, 'CHECK AND OK'), (2, 'MAY REQUIRE ATTENTION'), (3, 'REQUIRES IMMEDIATE ATTENTION')], default=1)),
                ('heating', models.IntegerField(choices=[(1, 'CHECK AND OK'), (2, 'MAY REQUIRE ATTENTION'), (3, 'REQUIRES IMMEDIATE ATTENTION')], default=1)),
                ('interior_other', models.CharField(blank=True, max_length=30, null=True)),
                ('engine_oil', models.IntegerField(choices=[(1, 'CHECK AND OK'), (2, 'MAY REQUIRE ATTENTION'), (3, 'REQUIRES IMMEDIATE ATTENTION')], default=1)),
                ('brake_fluid', models.IntegerField(choices=[(1, 'CHECK AND OK'), (2, 'MAY REQUIRE ATTENTION'), (3, 'REQUIRES IMMEDIATE ATTENTION')], default=1)),
                ('power_stearing', models.IntegerField(choices=[(1, 'CHECK AND OK'), (2, 'MAY REQUIRE ATTENTION'), (3, 'REQUIRES IMMEDIATE ATTENTION')], default=1)),
                ('washer', models.IntegerField(choices=[(1, 'CHECK AND OK'), (2, 'MAY REQUIRE ATTENTION'), (3, 'REQUIRES IMMEDIATE ATTENTION')], default=1)),
                ('belts_hoses', models.IntegerField(choices=[(1, 'CHECK AND OK'), (2, 'MAY REQUIRE ATTENTION'), (3, 'REQUIRES IMMEDIATE ATTENTION')], default=1)),
                ('coolant', models.IntegerField(choices=[(1, 'CHECK AND OK'), (2, 'MAY REQUIRE ATTENTION'), (3, 'REQUIRES IMMEDIATE ATTENTION')], default=1)),
                ('air_filter', models.IntegerField(choices=[(1, 'CHECK AND OK'), (2, 'MAY REQUIRE ATTENTION'), (3, 'REQUIRES IMMEDIATE ATTENTION')], default=1)),
                ('cabin_filter', models.IntegerField(choices=[(1, 'CHECK AND OK'), (2, 'MAY REQUIRE ATTENTION'), (3, 'REQUIRES IMMEDIATE ATTENTION')], default=1)),
                ('fuel_filter', models.IntegerField(choices=[(1, 'CHECK AND OK'), (2, 'MAY REQUIRE ATTENTION'), (3, 'REQUIRES IMMEDIATE ATTENTION')], default=1)),
                ('spark_plug', models.IntegerField(choices=[(1, 'CHECK AND OK'), (2, 'MAY REQUIRE ATTENTION'), (3, 'REQUIRES IMMEDIATE ATTENTION')], default=1)),
                ('underhood_other', models.CharField(blank=True, max_length=30, null=True)),
                ('battery_charge', models.IntegerField(choices=[(1, 'CHECK AND OK'), (2, 'MAY REQUIRE ATTENTION'), (3, 'REQUIRES IMMEDIATE ATTENTION')], default=1)),
                ('battery_condition', models.IntegerField(choices=[(1, 'CHECK AND OK'), (2, 'MAY REQUIRE ATTENTION'), (3, 'REQUIRES IMMEDIATE ATTENTION')], default=1)),
                ('cables', models.IntegerField(choices=[(1, 'CHECK AND OK'), (2, 'MAY REQUIRE ATTENTION'), (3, 'REQUIRES IMMEDIATE ATTENTION')], default=1)),
                ('brakes', models.IntegerField(choices=[(1, 'CHECK AND OK'), (2, 'MAY REQUIRE ATTENTION'), (3, 'REQUIRES IMMEDIATE ATTENTION')], default=1)),
                ('brake_lines', models.IntegerField(choices=[(1, 'CHECK AND OK'), (2, 'MAY REQUIRE ATTENTION'), (3, 'REQUIRES IMMEDIATE ATTENTION')], default=1)),
                ('steering', models.IntegerField(choices=[(1, 'CHECK AND OK'), (2, 'MAY REQUIRE ATTENTION'), (3, 'REQUIRES IMMEDIATE ATTENTION')], default=1)),
                ('shocks', models.IntegerField(choices=[(1, 'CHECK AND OK'), (2, 'MAY REQUIRE ATTENTION'), (3, 'REQUIRES IMMEDIATE ATTENTION')], default=1)),
                ('driveline', models.IntegerField(choices=[(1, 'CHECK AND OK'), (2, 'MAY REQUIRE ATTENTION'), (3, 'REQUIRES IMMEDIATE ATTENTION')], default=1)),
                ('exhaust', models.IntegerField(choices=[(1, 'CHECK AND OK'), (2, 'MAY REQUIRE ATTENTION'), (3, 'REQUIRES IMMEDIATE ATTENTION')], default=1)),
                ('fuel_lines', models.IntegerField(choices=[(1, 'CHECK AND OK'), (2, 'MAY REQUIRE ATTENTION'), (3, 'REQUIRES IMMEDIATE ATTENTION')], default=1)),
                ('under_vehicle_other', models.CharField(blank=True, max_length=30, null=True)),
                ('tread_depth', models.IntegerField(choices=[(1, '7/32" or greater'), (2, '3/32" to 6/32"'), (3, '2/32" or less')], default=1)),
                ('tread_lf', models.IntegerField(choices=[(1, 'CHECK AND OK'), (2, 'MAY REQUIRE ATTENTION'), (3, 'REQUIRES IMMEDIATE ATTENTION')], default=1)),
                ('tread_lr', models.IntegerField(choices=[(1, 'CHECK AND OK'), (2, 'MAY REQUIRE ATTENTION'), (3, 'REQUIRES IMMEDIATE ATTENTION')], default=1)),
                ('tread_rf', models.IntegerField(choices=[(1, 'CHECK AND OK'), (2, 'MAY REQUIRE ATTENTION'), (3, 'REQUIRES IMMEDIATE ATTENTION')], default=1)),
                ('tread_rr', models.IntegerField(choices=[(1, 'CHECK AND OK'), (2, 'MAY REQUIRE ATTENTION'), (3, 'REQUIRES IMMEDIATE ATTENTION')], default=1)),
                ('wear_lf', models.IntegerField(choices=[(1, 'CHECK AND OK'), (2, 'MAY REQUIRE ATTENTION'), (3, 'REQUIRES IMMEDIATE ATTENTION')], default=1)),
                ('wear_lr', models.IntegerField(choices=[(1, 'CHECK AND OK'), (2, 'MAY REQUIRE ATTENTION'), (3, 'REQUIRES IMMEDIATE ATTENTION')], default=1)),
                ('wear_rf', models.IntegerField(choices=[(1, 'CHECK AND OK'), (2, 'MAY REQUIRE ATTENTION'), (3, 'REQUIRES IMMEDIATE ATTENTION')], default=1)),
                ('wear_rr', models.IntegerField(choices=[(1, 'CHECK AND OK'), (2, 'MAY REQUIRE ATTENTION'), (3, 'REQUIRES IMMEDIATE ATTENTION')], default=1)),
                ('tpms', models.BooleanField(default=False)),
                ('air_lf', models.IntegerField(blank=True, default=0, null=True)),
                ('air_lr', models.IntegerField(blank=True, default=0, null=True)),
                ('air_rf', models.IntegerField(blank=True, default=0, null=True)),
                ('air_rr', models.IntegerField(blank=True, default=0, null=True)),
                ('alignment', models.BooleanField(default=False)),
                ('balance', models.BooleanField(default=False)),
                ('rotation', models.BooleanField(default=False)),
                ('new_tire', models.BooleanField(default=False)),
                ('repair_desc', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('date_updated', models.DateField(auto_now=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('inspected_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspect', to=settings.AUTH_USER_MODEL)),
                ('vin_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance', to='careta.car')),
            ],
        ),
    ]
