# Generated by Django 3.1.3 on 2020-11-13 00:48

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('careta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('insurance_id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=100)),
                ('telephone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('email', models.EmailField(max_length=50)),
                ('po_no', models.CharField(max_length=30)),
                ('date_issued', models.DateField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('cost', models.IntegerField(default=0)),
                ('insurance_no', models.IntegerField(default=1)),
                ('date_updated', models.DateField(auto_now=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance', to='careta.car')),
            ],
        ),
    ]
