# Generated by Django 3.1 on 2021-03-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
