# Generated by Django 3.1 on 2021-03-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careta', '0002_auto_20210309_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
