# Generated by Django 3.1 on 2021-03-31 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careta', '0002_auto_20210319_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspection',
            name='status',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='status',
        ),
        migrations.AlterField(
            model_name='inspection',
            name='gas_level',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='oil_level',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1),
        ),
    ]
