# Generated by Django 3.1 on 2021-07-21 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careta', '0002_userinfo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='image',
        ),
    ]
