# Generated by Django 3.1 on 2021-03-30 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('careta', '0002_auto_20210319_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_desc', models.CharField(blank=True, max_length=100, null=True)),
                ('job_remarks', models.CharField(blank=True, max_length=300, null=True)),
                ('job_startdate', models.DateField(null=True)),
                ('job_enddate', models.DateField(null=True)),
                ('job_startdate_actual', models.DateField(null=True)),
                ('job_enddate_actual', models.DateField(null=True)),
                ('job_actual_days', models.IntegerField(blank=True, default=0, null=True)),
                ('job_task_status_fm', models.CharField(blank=True, max_length=30, null=True)),
                ('job_task_status_mn', models.CharField(blank=True, max_length=30, null=True)),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='careta.car')),
                ('fieldman_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_fieldman', to=settings.AUTH_USER_MODEL)),
                ('manager_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_manager', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
