# Generated by Django 3.1 on 2021-03-19 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careta', '0002_maintenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
