# Generated by Django 3.1 on 2021-02-01 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('careta', '0003_auto_20210201_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Female'), ('F', 'Male')], max_length=2)),
                ('birthday', models.DateField()),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('address', models.CharField(max_length=100)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view_inventory', models.BooleanField(default=False)),
                ('can_add_inventory', models.BooleanField(default=False)),
                ('can_edit_inventory', models.BooleanField(default=False)),
                ('can_delete_inventory', models.BooleanField(default=False)),
                ('can_view_reports', models.BooleanField(default=False)),
                ('can_add_reports', models.BooleanField(default=False)),
                ('can_edit_reports', models.BooleanField(default=False)),
                ('can_delete_reports', models.BooleanField(default=False)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
