# Generated by Django 3.1 on 2021-03-30 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careta', '0003_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='car_id',
            new_name='car',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='fieldman_id',
            new_name='fieldman',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='manager_id',
            new_name='manager',
        ),
    ]
