# Generated by Django 3.1 on 2021-02-03 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careta', '0004_permission_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='can_add_task',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_add_users',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_delete_task',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_delete_users',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_edit_task',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_edit_users',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_view_task',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_view_users',
            field=models.BooleanField(default=False),
        ),
    ]
