# Generated by Django 3.1 on 2021-02-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careta', '0004_permissions_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissions',
            name='date_updated',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='date_updated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
