# Generated by Django 3.1 on 2021-03-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careta', '0004_auto_20210330_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='slug',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
