# Generated by Django 3.1 on 2021-10-25 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('careta', '0005_permission_can_approved_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='can_view_dashboard',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DashboardPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=30)),
                ('can_view_recieved_items', models.BooleanField(default=False)),
                ('can_view_operational_status', models.BooleanField(default=False)),
                ('can_view_expiring_cars', models.BooleanField(default=False)),
                ('can_view_expiry_table', models.BooleanField(default=False)),
                ('can_view_driver_inspection', models.BooleanField(default=False)),
                ('can_view_task', models.BooleanField(default=False)),
                ('can_view_ir', models.BooleanField(default=False)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
