# Generated by Django 3.1 on 2021-11-23 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careta', '0006_auto_20211025_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='birthday',
        ),
    ]
