# Generated by Django 3.1 on 2021-02-16 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('careta', '0006_report_reportimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportimage',
            name='report',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='careta.report'),
        ),
    ]
