# Generated by Django 3.1 on 2021-02-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careta', '0007_auto_20210216_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='bodyKey_date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='cigarettePlug_date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='decals_date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='ewd_date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='fan_date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='keychain_date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='plate_date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='tools_date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='unitKey_date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='userManual_date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='warrantyBook_date',
            field=models.CharField(max_length=10),
        ),
    ]
