# Generated by Django 3.1 on 2021-02-22 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('careta', '0008_auto_20210216_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='breake_lights',
            new_name='break_lights',
        ),
        migrations.RemoveField(
            model_name='car',
            name='chassis_no',
        ),
        migrations.AddField(
            model_name='car',
            name='fire_extinguisher',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='jack',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='wrench',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='battery_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='bodyKey_date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='body_builder',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='body_no',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='body_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='capacity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='cigarettePlug_date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='cr_date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='cs_no',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='current_loc',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='cylinder',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='dealer_email',
            field=models.EmailField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='dealer_phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='decals_date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='deliver_date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='delivery_location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='denomination',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='dr_codes',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='dr_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='ewd_date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='fabricator',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='fan_date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='field_office',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='gross_weight',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='keychain_date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='lto_cr',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='modified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='net_capacity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='net_weight',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='operational',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='or_cr',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='or_date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='or_no',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='permanent_loc',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='permanent_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='piston',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='plate_date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='plate_no',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='po_date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='po_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='procuring_entity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='release_year',
            field=models.IntegerField(blank=True, default=2021, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='remarks',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='sale_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='series',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='shipping_weight',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='si_no',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='tools_date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='top_load',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='unitKey_date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='userManual_date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='vat_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='vtf',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='warrantyBook_date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='bid_date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='bid_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='bid_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='client_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='cost',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date_updated',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='start_date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='cost',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='date_issued',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='date_updated',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='end_date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='insurance_no',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='po_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='start_date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='telephone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31, null=True),
        ),
        migrations.AlterField(
            model_name='tpl',
            name='cost',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tpl',
            name='date_issued',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tpl',
            name='email',
            field=models.EmailField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='tpl',
            name='end_date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tpl',
            name='insurance_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tpl',
            name='po_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tpl',
            name='start_date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tpl',
            name='telephone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='company',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='position',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('repair_id', models.AutoField(primary_key=True, serialize=False)),
                ('ro_no', models.CharField(max_length=10, unique=True)),
                ('incident_details', models.TextField(blank=True, max_length=200, null=True)),
                ('vms', models.CharField(max_length=50)),
                ('dealer', models.CharField(max_length=30)),
                ('schedule_date', models.DateField()),
                ('perform_date', models.DateField()),
                ('actual_findings', models.TextField(blank=True, max_length=200, null=True)),
                ('actual_remarks', models.TextField(blank=True, max_length=200, null=True)),
                ('repair_date', models.DateField()),
                ('action_taken', models.TextField(blank=True, max_length=200, null=True)),
                ('date_done', models.DateField()),
                ('status_repair', models.CharField(max_length=20)),
                ('remarks', models.TextField(blank=True, max_length=200, null=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('perform_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actual', to=settings.AUTH_USER_MODEL)),
                ('repair_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repair', to=settings.AUTH_USER_MODEL)),
                ('vin_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repair', to='careta.report')),
            ],
        ),
    ]
