# Generated by Django 3.1 on 2021-02-27 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careta', '0008_auto_20210228_0002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='breake_lights',
            new_name='break_lights',
        ),
    ]
