# Generated by Django 3.1 on 2021-02-22 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('careta', '0009_auto_20210222_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repair',
            name='vin_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repair', to='careta.car'),
        ),
    ]
