# Generated by Django 3.1 on 2021-03-03 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('careta', '0009_auto_20210228_0022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('mileage', models.IntegerField(default=0)),
                ('location', models.CharField(max_length=50)),
                ('cleanliness_exterior', models.BooleanField(default=False)),
                ('condition_rust', models.BooleanField(default=False)),
                ('decals', models.BooleanField(default=False)),
                ('windows', models.BooleanField(default=False)),
                ('rear_door', models.BooleanField(default=False)),
                ('mirror', models.BooleanField(default=False)),
                ('roof_rack', models.BooleanField(default=False)),
                ('rear_step', models.BooleanField(default=False)),
                ('seats', models.BooleanField(default=False)),
                ('seat_belts', models.BooleanField(default=False)),
                ('general_condition', models.BooleanField(default=False)),
                ('vehicle_documents', models.BooleanField(default=False)),
                ('main_beam', models.BooleanField(default=False)),
                ('dipped_beam', models.BooleanField(default=False)),
                ('side_lights', models.BooleanField(default=False)),
                ('tail_lights', models.BooleanField(default=False)),
                ('indicators', models.BooleanField(default=False)),
                ('break_lights', models.BooleanField(default=False)),
                ('reverse_lights', models.BooleanField(default=False)),
                ('hazard_light', models.BooleanField(default=False)),
                ('rear_fog_lights', models.BooleanField(default=False)),
                ('interior_lights', models.BooleanField(default=False)),
                ('screen_washer', models.BooleanField(default=False)),
                ('wiper_blades', models.BooleanField(default=False)),
                ('horn', models.BooleanField(default=False)),
                ('radio', models.BooleanField(default=False)),
                ('front_fog_lights', models.BooleanField(default=False)),
                ('air_conditioning', models.BooleanField(default=False)),
                ('cleanliness_engine_bay', models.BooleanField(default=False)),
                ('washer_fluid', models.BooleanField(default=False)),
                ('coolant_level', models.BooleanField(default=False)),
                ('brake_fluid_level', models.BooleanField(default=False)),
                ('power_steering_fluid', models.BooleanField(default=False)),
                ('gas_level', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
                ('oil_level', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
                ('tyres', models.BooleanField(default=False)),
                ('front_visual', models.BooleanField(default=False)),
                ('rear_visual', models.BooleanField(default=False)),
                ('spare_visual', models.BooleanField(default=False)),
                ('wheel_brace', models.BooleanField(default=False)),
                ('jack', models.BooleanField(default=False)),
                ('front_right_wheel', models.BooleanField(default=False)),
                ('front_left_wheel', models.BooleanField(default=False)),
                ('rear_right_wheel', models.BooleanField(default=False)),
                ('rear_left_wheel', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to=settings.AUTH_USER_MODEL)),
                ('vin_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='careta.car')),
            ],
        ),
        migrations.CreateModel(
            name='InspectiontImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='images/')),
                ('report', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='careta.inspection')),
            ],
        ),
        migrations.RemoveField(
            model_name='reportimage',
            name='report',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='ReportImage',
        ),
    ]
