# Generated by Django 3.1 on 2021-03-04 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careta', '0010_auto_20210303_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspection',
            old_name='report_id',
            new_name='inspection_id',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='location',
        ),
        migrations.RemoveField(
            model_name='repair',
            name='location',
        ),
    ]
