# Generated by Django 3.1 on 2021-02-23 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('careta', '0010_auto_20210222_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('cost_id', models.AutoField(primary_key=True, serialize=False)),
                ('cost_type', models.CharField(choices=[('P', 'Parts'), ('L', 'Labor')], default='L', max_length=1)),
                ('particulars', models.CharField(max_length=50)),
                ('cost', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('date_updated', models.DateField(auto_now=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('ro_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost', to='careta.repair')),
            ],
        ),
    ]
