# Generated by Django 3.1 on 2021-08-17 05:50

import datetime
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_auto_20210708_1048'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IR',
            fields=[
                ('ir_id', models.AutoField(primary_key=True, serialize=False)),
                ('ir_no', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('weiver', models.BooleanField(default=False)),
                ('req_name', models.CharField(blank=True, max_length=50, null=True)),
                ('project_name', models.CharField(blank=True, max_length=30, null=True)),
                ('sub_project', models.CharField(blank=True, max_length=30, null=True)),
                ('region', models.CharField(blank=True, max_length=30, null=True)),
                ('exact_loc', models.CharField(blank=True, max_length=70, null=True)),
                ('vehicle_supp', models.CharField(blank=True, max_length=50, null=True)),
                ('odometer', models.CharField(blank=True, max_length=20, null=True)),
                ('repair_type', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('me', 'Mehcanical'), ('el', 'Electrical'), ('ba', 'Battery'), ('ti', 'Tires'), ('pm', 'PMS'), ('ac', 'Accident'), ('ot', 'Others')], max_length=2, null=True)),
                ('damaged_parts', models.TextField(blank=True, max_length=200, null=True)),
                ('incedent_loc', models.CharField(blank=True, max_length=20, null=True)),
                ('problem_obs', models.TextField(blank=True, max_length=200, null=True)),
                ('recommendation', models.TextField(blank=True, max_length=200, null=True)),
                ('date_time', models.DateTimeField(default=datetime.datetime.now)),
                ('prepared_by', models.CharField(blank=True, max_length=50, null=True)),
                ('noted_by', models.CharField(blank=True, max_length=50, null=True)),
                ('admin_name', models.CharField(blank=True, max_length=50, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=50, null=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('body_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ir_body_no', to='car.car')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='ir_no',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task', to='task.ir'),
        ),
    ]
