# Generated by Django 3.1 on 2021-08-18 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_auto_20210818_1413'),
        ('task', '0002_auto_20210817_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='check_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ck_task', to='report.checklist'),
        ),
    ]
