# Generated by Django 3.1 on 2021-08-18 08:42

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_task_check_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ir',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='ir',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ir',
            name='repair_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('me', 'Mehcanical'), ('el', 'Electrical'), ('ba', 'Battery'), ('ti', 'Tires'), ('pm', 'PMS'), ('ac', 'Accident'), ('ot', 'Others')], max_length=20, null=True),
        ),
    ]
