# Generated by Django 3.1 on 2021-09-07 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0013_auto_20210907_1522'),
        ('task', '0005_auto_20210826_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='ir',
            name='area',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='check_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ck_task', to='report.checklist'),
        ),
        migrations.AlterField(
            model_name='task',
            name='ir_no',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task', to='task.ir'),
        ),
    ]
