# Generated by Django 3.1 on 2021-10-01 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_ir_operational'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ir',
            name='area',
        ),
        migrations.RemoveField(
            model_name='ir',
            name='exact_loc',
        ),
    ]
