# Generated by Django 3.1 on 2021-10-01 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_auto_20211001_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ir',
            name='vehicle_supp',
        ),
    ]
