# Generated by Django 3.1 on 2021-10-25 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_task_task_status_bm'),
        ('task', '0010_ir_remarks'),
    ]

    operations = [
    ]
